[pytest]

# Indique à Pytest d'ajouter la racine du projet au PYTHONPATH lors de l'exécution des tests.
# 
# Sans cette configuration, Pytest ne trouvait pas le package :
# from api.api_home_credit_scoring import app
#
# et levait l'erreur :
# ModuleNotFoundError: No module named 'api'

pythonpath = .